name: nodejs

type: nodejs:10

relationships:
  headless: "headless:http"

crons:
  cleanup:
    spec: '*/30 * * * *'
    cmd: rm pdfs/* && rm screenshots/*

web:
  commands:
    start: "node index.js"
  locations:
    "/screenshots":
        root: "screenshots"
        scripts: false
    "/diff":
        root: "diff"
        scripts: false

mounts:
  "/pdfs": "shared:files/pdfs"
  "/screenshots": "shared:files/screenshots"
  "/diff": "shared:files/diff"

disk: 512
